sudo: false
language: node_js
node_js:
- '10.15.0'
cache: npm
notifications:
  email: false

jobs:
  include:
  - stage: build
    script: npm run build
  - stage: test
    script: npm run test:travis
  - stage: release
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release
      on:
        branch: master
        condition: "\"$GITHUB_TOKEN\" != \"\""
